"""empty message

Revision ID: 0bad45334c19
Revises: 0afac563dce1
Create Date: 2019-05-29 12:16:43.488592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bad45334c19'
down_revision = '0afac563dce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kgs_games', sa.Column('black_rank', sa.Integer(), nullable=True))
    op.add_column('kgs_games', sa.Column('white_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_kgs_games_black'), 'kgs_games', ['black'], unique=False)
    op.create_index(op.f('ix_kgs_games_white'), 'kgs_games', ['white'], unique=False)
    op.drop_column('kgs_games', 'setup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kgs_games', sa.Column('setup', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_kgs_games_white'), table_name='kgs_games')
    op.drop_index(op.f('ix_kgs_games_black'), table_name='kgs_games')
    op.drop_column('kgs_games', 'white_rank')
    op.drop_column('kgs_games', 'black_rank')
    # ### end Alembic commands ###
