"""empty message

Revision ID: 1a59846f54c1
Revises: 3d1ce254cc58
Create Date: 2019-05-27 19:41:45.039188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a59846f54c1'
down_revision = '3d1ce254cc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_con_1', 'game', ['tournament', 'date', 'round', 'black', 'white'])
    op.drop_constraint('game_tournament_date_round_black_white_key', 'game', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('game_tournament_date_round_black_white_key', 'game', ['tournament', 'date', 'round', 'black', 'white'])
    op.drop_constraint('uniq_con_1', 'game', type_='unique')
    # ### end Alembic commands ###
