"""empty message

Revision ID: 3d1ce254cc58
Revises: 651a588d6519
Create Date: 2019-05-27 19:40:48.095523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1ce254cc58'
down_revision = '651a588d6519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'game', ['tournament', 'date', 'round', 'black', 'white'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='unique')
    # ### end Alembic commands ###
