"""empty message

Revision ID: 651a588d6519
Revises: db6d2ee989f5
Create Date: 2019-05-27 12:01:18.512804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651a588d6519'
down_revision = 'db6d2ee989f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('ayd_game', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('eyd_game', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_game_ayd_game'), 'game', ['ayd_game'], unique=False)
    op.create_index(op.f('ix_game_eyd_game'), 'game', ['eyd_game'], unique=False)
    op.drop_index('ix_game_yd_game', table_name='game')
    op.drop_column('game', 'yd_game')
    op.add_column('user', sa.Column('ayd_member', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('eyd_member', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_ayd_member'), 'user', ['ayd_member'], unique=False)
    op.create_index(op.f('ix_user_eyd_member'), 'user', ['eyd_member'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_eyd_member'), table_name='user')
    op.drop_index(op.f('ix_user_ayd_member'), table_name='user')
    op.drop_column('user', 'eyd_member')
    op.drop_column('user', 'ayd_member')
    op.add_column('game', sa.Column('yd_game', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_game_yd_game', 'game', ['yd_game'], unique=False)
    op.drop_index(op.f('ix_game_eyd_game'), table_name='game')
    op.drop_index(op.f('ix_game_ayd_game'), table_name='game')
    op.drop_column('game', 'eyd_game')
    op.drop_column('game', 'ayd_game')
    # ### end Alembic commands ###
