"""empty message

Revision ID: 737cb0c12b7c
Revises: 0bad45334c19
Create Date: 2019-05-29 12:19:12.461213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737cb0c12b7c'
down_revision = '0bad45334c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kgs_games', sa.Column('b_rank', sa.Integer(), nullable=True))
    op.add_column('kgs_games', sa.Column('w_rank', sa.Integer(), nullable=True))
    op.drop_column('kgs_games', 'black_rank')
    op.drop_column('kgs_games', 'white_rank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kgs_games', sa.Column('white_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('kgs_games', sa.Column('black_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('kgs_games', 'w_rank')
    op.drop_column('kgs_games', 'b_rank')
    # ### end Alembic commands ###
