"""empty message

Revision ID: 988a752a54d8
Revises: 737cb0c12b7c
Create Date: 2019-05-29 13:49:30.013027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988a752a54d8'
down_revision = '737cb0c12b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_game_con', 'games', ['tournament', 'round', 'black', 'white', 'date'])
    op.create_unique_constraint('uniq_kgs_game_con', 'kgs_games', ['date', 'black', 'white'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_kgs_game_con', 'kgs_games', type_='unique')
    op.drop_constraint('uniq_game_con', 'games', type_='unique')
    # ### end Alembic commands ###
