"""empty message

Revision ID: a3255287a6d4
Revises: 
Create Date: 2019-05-27 09:13:40.788208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3255287a6d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('kgs_username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kgs_username'), 'user', ['kgs_username'], unique=True)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament', sa.String(length=128), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('black', sa.String(length=64), nullable=True),
    sa.Column('white', sa.String(length=64), nullable=True),
    sa.Column('b_win', sa.Boolean(), nullable=True),
    sa.Column('w_win', sa.Boolean(), nullable=True),
    sa.Column('yd_game', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['black'], ['user.kgs_username'], ),
    sa.ForeignKeyConstraint(['white'], ['user.kgs_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_round'), 'game', ['round'], unique=False)
    op.create_index(op.f('ix_game_tournament'), 'game', ['tournament'], unique=False)
    op.create_index(op.f('ix_game_yd_game'), 'game', ['yd_game'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_yd_game'), table_name='game')
    op.drop_index(op.f('ix_game_tournament'), table_name='game')
    op.drop_index(op.f('ix_game_round'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_user_kgs_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
