"""empty message

Revision ID: db6d2ee989f5
Revises: a3255287a6d4
Create Date: 2019-05-27 10:19:57.838803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6d2ee989f5'
down_revision = 'a3255287a6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_column('game', 'date')
    # ### end Alembic commands ###
